# Site Build Settings

# Jekyll-paginate-v2 configuration
# pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

# jekyll-paginate configuration
paginate: 5

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Customize atom feed settings (Jekyll-Feed configuration)
title: "The Archive"
description: "The info you're searching for"
author: "Shiraj Shrestha"

# Uncomment if RSS 2.0 is preferred over Atom
# feed:
#   path: rss-feed.xml

# Base URL
baseurl: "/blogs"
sass:
  sass_dir: _sass
  style: compressed
